/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Control;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import model.Car;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Flinkerfyr
 */
public class JFrameCarHandler extends javax.swing.JFrame {

    private Control control;

    /**
     * Creates new form JFrameCarHandler
     */
    public JFrameCarHandler(Control control) {
        initComponents();
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        this.control = control;
        jTableCarList.setModel(updateCarTableModel());
        fillPeriodComboBox();
        this.setVisible(true);
    }

    public DefaultTableModel updateCarTableModel() {

        DefaultTableModel model = new DefaultTableModel();
        
        model.addColumn("Brand");
        model.addColumn("Model");
        model.addColumn("Year");
        model.addColumn("Carvalue");
        model.addColumn("Topspeed");
        model.addColumn("Seats");
        model.addColumn("Trunk");
        model.setRowCount(control.getCarList().size());
        int r=0;
        
        for (Car s : control.getCarList()) {
            model.setValueAt(s.getBrand(), r, 0);
            model.setValueAt(s.getModel(), r, 1);
            model.setValueAt(s.getYear(), r, 2);
            model.setValueAt(s.getCarValue(), r, 3);
            model.setValueAt(s.getTopSpeed(), r, 4);
            model.setValueAt(s.getNumberOfSeats(), r, 5);
            model.setValueAt(s.getTrunkPresent(), r, 6);
            r++;
        }

        return model;
    }

    public void fillPeriodComboBox() {
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
        dcbm.addElement("Monthly");
        dcbm.addElement("Weekly");
        jComboBoxPeriode.setModel(dcbm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jButtonShowAllCarsSortedByHighestEarning = new javax.swing.JButton();
        jLabelCarTitle = new javax.swing.JLabel();
        jButtonShowAllCarsRentedByGuestID = new javax.swing.JButton();
        jButtonShowAllAvailableCars = new javax.swing.JButton();
        jButtonShowAllCarsRentedOut = new javax.swing.JButton();
        jButtonShowNumberOfCarsRentedOut = new javax.swing.JButton();
        jButtonShowTotalDistanceDrivenForAllCars = new javax.swing.JButton();
        jButtonShowMoneyEarnedForAllCars = new javax.swing.JButton();
        jButtonShowCarsWhichNeedRepair = new javax.swing.JButton();
        jButtonShowAllCarsSortedByMostRented = new javax.swing.JButton();
        jComboBoxPeriode = new javax.swing.JComboBox<>();
        jLabelCurrently = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarList = new javax.swing.JTable();
        jButtonDisplayRentingInformation = new javax.swing.JButton();
        jButtonSearchCar = new javax.swing.JButton();
        jButtonRentCar = new javax.swing.JButton();
        jButtonAddCar = new javax.swing.JButton();
        jButtonDeleteCar = new javax.swing.JButton();
        jButtonReturnCar = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonShowAllCarsSortedByHighestEarning.setText("Show all cars sorted by highest earnings");
        jButtonShowAllCarsSortedByHighestEarning.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowAllCarsSortedByHighestEarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllCarsSortedByHighestEarningActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAllCarsSortedByHighestEarning, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 320, -1));

        jLabelCarTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelCarTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCarTitle.setText("Car Administration");
        getContentPane().add(jLabelCarTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 930, 39));

        jButtonShowAllCarsRentedByGuestID.setText("Show all cars rented by guest ID");
        jButtonShowAllCarsRentedByGuestID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowAllCarsRentedByGuestID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllCarsRentedByGuestIDActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAllCarsRentedByGuestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 320, -1));

        jButtonShowAllAvailableCars.setText("Show all available cars");
        jButtonShowAllAvailableCars.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowAllAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllAvailableCarsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAllAvailableCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 320, -1));

        jButtonShowAllCarsRentedOut.setText("Show all cars rented out");
        jButtonShowAllCarsRentedOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowAllCarsRentedOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllCarsRentedOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAllCarsRentedOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 320, -1));

        jButtonShowNumberOfCarsRentedOut.setText("Show number of cars rented out");
        jButtonShowNumberOfCarsRentedOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowNumberOfCarsRentedOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowNumberOfCarsRentedOutActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowNumberOfCarsRentedOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 320, -1));

        jButtonShowTotalDistanceDrivenForAllCars.setText("Show total distance driven for all cars");
        jButtonShowTotalDistanceDrivenForAllCars.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowTotalDistanceDrivenForAllCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowTotalDistanceDrivenForAllCarsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowTotalDistanceDrivenForAllCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 320, -1));

        jButtonShowMoneyEarnedForAllCars.setText("Show money earned for all cars");
        jButtonShowMoneyEarnedForAllCars.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowMoneyEarnedForAllCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowMoneyEarnedForAllCarsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowMoneyEarnedForAllCars, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 320, -1));

        jButtonShowCarsWhichNeedRepair.setText("Show cars which need repair");
        jButtonShowCarsWhichNeedRepair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowCarsWhichNeedRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowCarsWhichNeedRepairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowCarsWhichNeedRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 320, -1));

        jButtonShowAllCarsSortedByMostRented.setText("Show all cars sorted by most rented");
        jButtonShowAllCarsSortedByMostRented.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonShowAllCarsSortedByMostRented.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowAllCarsSortedByMostRentedActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonShowAllCarsSortedByMostRented, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 320, -1));

        jComboBoxPeriode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeriodeActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPeriode, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 310, -1));

        jLabelCurrently.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelCurrently.setText("Currently");
        jLabelCurrently.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabelCurrently, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 300, 20));

        jTableCarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCarList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 590, -1));

        jButtonDisplayRentingInformation.setText("Display renting information");
        getContentPane().add(jButtonDisplayRentingInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 260, -1));

        jButtonSearchCar.setText("Search Car");
        getContentPane().add(jButtonSearchCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 140, -1));

        jButtonRentCar.setText("Rent Car");
        getContentPane().add(jButtonRentCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 140, -1));

        jButtonAddCar.setText("Add Car");
        getContentPane().add(jButtonAddCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 130, -1));

        jButtonDeleteCar.setText("Delete Car");
        getContentPane().add(jButtonDeleteCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 130, -1));

        jButtonReturnCar.setText("Return Car");
        jButtonReturnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnCarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReturnCar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowAllCarsSortedByHighestEarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllCarsSortedByHighestEarningActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllCarsSortedByHighestEarningActionPerformed

    private void jButtonShowAllCarsRentedByGuestIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllCarsRentedByGuestIDActionPerformed
        control.sortAllCarsByGuestID();//Sort cars in control bu guest ID
        updateCarTableModel();//Update table model from control
    }//GEN-LAST:event_jButtonShowAllCarsRentedByGuestIDActionPerformed

    private void jButtonShowAllAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllAvailableCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllAvailableCarsActionPerformed

    private void jButtonShowAllCarsRentedOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllCarsRentedOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllCarsRentedOutActionPerformed

    private void jButtonShowNumberOfCarsRentedOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowNumberOfCarsRentedOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowNumberOfCarsRentedOutActionPerformed

    private void jButtonShowTotalDistanceDrivenForAllCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowTotalDistanceDrivenForAllCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowTotalDistanceDrivenForAllCarsActionPerformed

    private void jButtonShowMoneyEarnedForAllCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowMoneyEarnedForAllCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowMoneyEarnedForAllCarsActionPerformed

    private void jButtonShowCarsWhichNeedRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowCarsWhichNeedRepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowCarsWhichNeedRepairActionPerformed

    private void jButtonShowAllCarsSortedByMostRentedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowAllCarsSortedByMostRentedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonShowAllCarsSortedByMostRentedActionPerformed

    private void jComboBoxPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeriodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeriodeActionPerformed

    private void jButtonReturnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnCarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturnCarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddCar;
    private javax.swing.JButton jButtonDeleteCar;
    private javax.swing.JButton jButtonDisplayRentingInformation;
    private javax.swing.JButton jButtonRentCar;
    private javax.swing.JButton jButtonReturnCar;
    private javax.swing.JButton jButtonSearchCar;
    private javax.swing.JButton jButtonShowAllAvailableCars;
    private javax.swing.JButton jButtonShowAllCarsRentedByGuestID;
    private javax.swing.JButton jButtonShowAllCarsRentedOut;
    private javax.swing.JButton jButtonShowAllCarsSortedByHighestEarning;
    private javax.swing.JButton jButtonShowAllCarsSortedByMostRented;
    private javax.swing.JButton jButtonShowCarsWhichNeedRepair;
    private javax.swing.JButton jButtonShowMoneyEarnedForAllCars;
    private javax.swing.JButton jButtonShowNumberOfCarsRentedOut;
    private javax.swing.JButton jButtonShowTotalDistanceDrivenForAllCars;
    private javax.swing.JComboBox<String> jComboBoxPeriode;
    private javax.swing.JLabel jLabelCarTitle;
    private javax.swing.JLabel jLabelCurrently;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarList;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
