/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Control;
import java.util.Collections;
import javax.swing.table.DefaultTableModel;
import model.Car;
import model.Guest;

/**
 *
 * @author scheldejonas
 */
public class JframeGuestList extends javax.swing.JFrame {
    private Control control;

    /**
     * Creates new form JframeGuestList
     */
    public JframeGuestList(Control control) {
        initComponents();
        this.control = control;
        updateGuestListTable();
        this.setVisible(true);
    }
    
    public void updateGuestListTable() {
        DefaultTableModel model = new DefaultTableModel();
        
        Collections.sort(control.getGuestListForDisplay()); //Sort list of cars with Arrays.sort (Remenber to make Cars comparable by GuestID)
        
        model.addColumn("CustomerID");
        model.addColumn("Name");
        model.setRowCount(control.getGuestListForDisplay().size());
        int row = 0;
        
        for (Guest guest : control.getGuestListForDisplay()) {
            model.setValueAt(guest.getID(), row, 0);
            model.setValueAt(guest.getName(), row, 1);
            row++;
        }
        jTableGuestList.setModel(model);
        jTableGuestList.setEditingColumn(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGuestList = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonContinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableGuestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGuestList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, 525, 283));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Guest List - Choose guest ID and hit ok.");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 525, 34));

        jButtonContinue.setText("Continue");
        jButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinueActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinue, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinueActionPerformed
        int recievedGuestID = Integer.parseInt(jTableGuestList.getValueAt(jTableGuestList.getSelectedRow(), 0).toString());
        control.setChoosenGuest(recievedGuestID);
        this.dispose();
    }//GEN-LAST:event_jButtonContinueActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGuestList;
    // End of variables declaration//GEN-END:variables
}
